/**
 * Curated X sources for market context (not trade signals).
 * Sync category/sourceType with `src/services/xFeedCurated.ts` when editing.
 */

export const DEFAULT_CURATED_HANDLES = [
  'alphatrends',
  'traderstewie',
  'Qullamaggie',
  'markminervini',
  'unusual_whales',
  'DeItaone',
  'StockMKTNewz',
  'SMBcapital',
  'ChartGuys',
  'TradeTheNews',
  'MarketRebels',
]

/** @type {Record<string, { category: 'technical' | 'news' | 'education', sourceType: 'trader' | 'news' | 'education' }>} */
export const HANDLE_META = Object.fromEntries(
  [
    // A — Technical / swing / intraday
    ['alphatrends', { category: 'technical', sourceType: 'trader' }],
    ['traderstewie', { category: 'technical', sourceType: 'trader' }],
    ['qullamaggie', { category: 'technical', sourceType: 'trader' }],
    ['markminervini', { category: 'technical', sourceType: 'trader' }],
    // B — News / momentum / context
    ['unusual_whales', { category: 'news', sourceType: 'news' }],
    ['deitaone', { category: 'news', sourceType: 'news' }],
    ['stockmktnewz', { category: 'news', sourceType: 'news' }],
    ['tradethenews', { category: 'news', sourceType: 'news' }],
    ['marketrebels', { category: 'news', sourceType: 'news' }],
    // C — Educational / process
    ['smbcapital', { category: 'education', sourceType: 'education' }],
    ['chartguys', { category: 'education', sourceType: 'education' }],
  ].map(([h, m]) => [h.toLowerCase(), m]),
)

export const MARKET_ETFS = new Set(['SPY', 'QQQ', 'IWM', 'DIA'])

/** Liquid US symbols for bare-token matching (reduces false positives). */
export const LIQUID_SYMBOLS = new Set([
  'AAPL',
  'AMD',
  'AMZN',
  'ARM',
  'AVGO',
  'BA',
  'BABA',
  'COIN',
  'CRM',
  'CRWD',
  'CVNA',
  'DIS',
  'GOOG',
  'GOOGL',
  'GS',
  'HD',
  'HOOD',
  'INTC',
  'IWM',
  'JPM',
  'LLY',
  'LULU',
  'MA',
  'META',
  'MRNA',
  'MSFT',
  'MSTR',
  'MU',
  'NFLX',
  'NOW',
  'NVDA',
  'ORCL',
  'PANW',
  'PLTR',
  'PYPL',
  'QCOM',
  'QQQ',
  'RIVN',
  'ROKU',
  'SHOP',
  'SMCI',
  'SNOW',
  'SPY',
  'TSLA',
  'TSM',
  'UBER',
  'UNH',
  'UPS',
  'V',
  'WMT',
  'XOM',
])

/** Lowercase tokens that look like tickers but are not. */
/** Words / abbreviations that are not equity tickers (avoid bare-token false positives). */
export const TICKER_BLOCKLIST = new Set(
  [
    'CEO',
    'CFO',
    'IPO',
    'EPS',
    'GDP',
    'CPI',
    'FOMC',
    'ETF',
    'ATH',
    'ATHS',
    'THE',
    'AND',
    'FOR',
    'ARE',
    'BUT',
    'NOT',
    'YOU',
    'ALL',
    'CAN',
    'HER',
    'HIS',
    'OUR',
    'OUT',
    'NEW',
    'OLD',
    'WAY',
    'WHO',
    'WHY',
    'HOW',
    'ITS',
    'MAY',
    'NOW',
    'OFF',
    'ONE',
    'OWN',
    'PUT',
    'RUN',
    'SAY',
    'SEE',
    'SHE',
    'TOO',
    'TOP',
    'TRY',
    'TWO',
    'USE',
    'YES',
    'YET',
    'GET',
    'GOT',
    'HAD',
    'HAS',
    'LET',
    'LOT',
    'LOW',
    'DAY',
    'END',
    'DID',
    'FEW',
    'FED',
  ].map((s) => s.toLowerCase()),
)
